Created a desktop version of portfolio with media querries.
Fsher07/Portfolio-Desktop-version pull request #1
Opened 2022-02-17 13:16 UTC by Fsher07

Same template was used as in the previous project.

2022-02-17 14:04 UTC, keroloussamy requested changes
Hi @Fsher07, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly fix your mobile version because it's get broken when you made the desktop version. Your design should match both the mobile and the desktop versions. [The template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471) that you have to follow.

![image](https://user-images.githubusercontent.com/35535130/154496378-bed56167-ab31-4ab1-a74c-2dcd48fe9cf8.png)

And here 
![image](https://user-images.githubusercontent.com/35535130/154496493-c0c94251-1305-48d1-9554-587892e38819.png)




![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 14:04 UTC, keroloussamy commented on style.css
> +}
- [ ] Kindly make the `width` bigger to match the Figma design.

| Your design  | Figma design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/35535130/154497283-00d7305e-9d42-47ff-a7d1-780deb63ca50.png) | ![image](https://user-images.githubusercontent.com/35535130/154497469-7cbf553b-8524-4ee1-b0f0-2d6561b2e5e3.png) |

2022-02-17 17:35 UTC, thecodechaser requested changes
## Hi @Fsher07 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [ ]  Check the comments under the review.
- [ ]  As requested by the previous reviewer your mobile version is get broken when you made the desktop version. Your design should match both the mobile and the desktop versions with the [figme template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471)

See these images for reference 

![Screenshot (158)](https://user-images.githubusercontent.com/83803414/154536687-316e52cf-5de0-4885-bbcc-df3faa520910.png)
![Screenshot (159)](https://user-images.githubusercontent.com/83803414/154536695-0366d65d-e028-48e5-96dc-4b05621902a4.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 17:35 UTC, thecodechaser commented on style.css
> +  }
- [ ] [optional] I am marking this change as optional because it was missed by the previous reviewer, But I recommend you must consider this and update your code. You should go with the mobile-first approach where you design your webpage first for mobile screens and using media queries (min-width) you apply the styles for desktop screens here you are using max-width and it's following the desktop-first approach.

2022-02-18 17:28 UTC, Fsher07 commented
Thank you for replying. Now the mobile version works properly. I fixed the text in the form section. Now, it leans right.

2022-02-18 17:35 UTC, prolajumokeoni commented
> Thank you for replying. Now the mobile version works properly. I fixed the text in the form section. Now, it leans right.

###OPTIONAL 
- Always add a short summary pull request message describing what your pull request is about 👍🏿

2022-02-18 17:42 UTC, prolajumokeoni commented on index.html
> +  </form>
- [ ] Weldone implementing this design, you can also add Last Name input so it matches the original design 👍🏿

2022-02-18 17:47 UTC, prolajumokeoni approved these changes
Hi @Fsher07 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


![all-done-gif](https://user-images.githubusercontent.com/69638013/154735303-0c34354a-61e3-4dea-a9d4-3706b75fd3b8.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni .

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 17:51 UTC, merged